[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.build]
cmds = ["npm ci", "NODE_OPTIONS='--require ./polyfill.cjs' npx next build"]

[start]
cmd = "NODE_OPTIONS='--require ./polyfill.cjs' npx next start"
